### ISSUE TITLE
Post Tweet 

### ISSUE THREAD

**Issue by FelicityHarvard** [Intro-to-SE-Spring-2020/Achievers#1]
As a user, I want to be able to post a tweets so I can communicate with others. 
@aqd14

**Comment by daltonrpruitt** [comment]
Task Breakdown:
- [ ] Complete User Home Page (HTML/CSS/etc.)
- [ ] Create place in database for tweets to be stored
- [ ] Implement tweet creation from Home page to database (upon "post" button)

**Comment by daltonrpruitt** [comment]
Story points : 7
