### ISSUE TITLE
Like Tweet

### ISSUE THREAD

**Issue by FelicityHarvard** [Intro-to-SE-Spring-2020/Achievers#2]
As a user I want to be able to like a tweet so that I can show my appreciation towards others tweets
@aqd14

**Comment by daltonrpruitt** [comment]
Task Breakdown:
- [ ] Complete User Home Page (HTML/CSS/etc.)
- [ ] Add "liked tweets" container to User Account in Database
- [ ] Add functionality for user to make a tweet "liked" by pressing "Like" button

Optional:
- [ ] Make "Like" button nice

**Comment by daltonrpruitt** [comment]
Acceptance Test:
1. Type username into "Username" box
2. Type password into "Password" box
3. Click the "Create Account" button
4. Receive a "Success" message
5. Show new account's home page

**Comment by daltonrpruitt** [comment]
Story points : 3
