### ISSUE TITLE
Create User Account

### ISSUE THREAD

**Issue by FelicityHarvard** [Intro-to-SE-Spring-2020/Achievers#4]
As a user I want to be able to create an account so that I can easily access my follower's tweets and followers can easily access the user's tweets
@aqd14

**Comment by FelicityHarvard** [comment]
Steps for Story:  
    -Create the Class Diagram; To Be Done by Felicity Harvard  
    - Create the Sequence Diagram; Finished by Dalton Pruitt
    - Create the HTML page for Create Account; Finished by Eddie Caveness
    - Implementation of Create Account; Finished by Caleb Mills

**Comment by FelicityHarvard** [comment]
Completed for Sprint 1.

**Comment by daltonrpruitt** [comment]
Story points : 6

**Comment by CTMills** [comment]
Finished the feature and closing the issue
