### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by FelicityHarvard** [Intro-to-SE-Spring-2020/Achievers#5]
As a user I want to be able to login to my account so that I can access the information linked to my account.
@aqd14

**Comment by daltonrpruitt** [comment]
Steps: 

- [x] Sequence Diagram for behavior
- [x] Complete Login HTML page 
- [ ] Create interface between Login page and database
- [ ] Show error message upon unsuccessful login
- [ ] Show user page after successful login

**Comment by FelicityHarvard** [comment]
Steps for Story:
- Create the Sequence Diagram; Finished by Dalton Pruitt
- Create the HTML page for Create Account; Finished by Eddie Caveness
- Implementation of Create Account; Finished by Caleb Mills

**Comment by daltonrpruitt** [comment]
This was completed during Sprint 2.

**Comment by daltonrpruitt** [comment]
Acceptance Test:
1. Enter username into "Username" box
2. Enter password into "Password " box
3. Click "Login"
4. Switch to the user's "Home" page

**Comment by daltonrpruitt** [comment]
Story points : 3
